language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: OlByke4sSdgzMXOHwawpANploheJ+EYbznv3ITkE6N9LkQnaLu5mslj+sWvQzT5fW7qE5orgTM8ZDR9FeJADkwC1WPO9drdk9yDvOJWnh+Wn45kAlGNLAQmbfq3J3CaxNo5ULHRJVFmVk2aWNmC9Y8va2ICilppMzVeDugsNFvT+UbJfUhQQAN0QeG0aYBnD7L7P2spp1CuD7I1PN74dpgjKgnYS8K5uLf1AUKinOl3jhH1yUKitF+FsB3KUpymfVL/uYZ02KF0XcmtKMarJi178CeKj3E0hqrNjtDiXPZC6paAk2AzMdajf3TX+YuVIF+/Iy0obJsc7Sik6+5H3O2FiZkCq4y2kCFZJ1N+vJDRbJTiHbmQiDLRvnp2BON9OdOuC0s7oA2zXv7bKvKj8mVCMlC1EKDO+ssOX9+mmC6LiEC9zNWs4uQu4NgooNvr+qdRiXb4ZFXkam4zII24WGvZtB674c+3J9tEUWAIpgGm9Ec7JQD4tQLqYMzaBcc4zQVsQ8wpBBMt6qNK2Oaao8TwWEnNSGz51bjSILiN4cFxK8CZ+LtuLGxHF7841hoO9/p00JoEicVTpDdEKKZsFfZE3AEQj4BkCVPqSoM93rjU+OE8xEE4xD9rpFaceaYMMtOtU2pZGv3vnLI0oFIp2O8hGfy2F2ce1nswTTJV6la8=
  app: brewtrackr
  on:
    repo: wjypark94/brew-trackr
